---
sudo: false
language: perl
perl:
  - '5.20'
branches:
  only:
    - master
env:
  global:
    - AUTHOR_TESTING=0
    - COVERAGE_URI="https://roxsoft.co.uk/coverage/report/%s"
    - secure: MDbXs58X/qbpOzboTdbOtIh9Bc9pT0xmNV5fRFd8KDSoEw8j6QbybyltKf33R2Vobs3jNhohfyYrXBkAXIJk4Mf6viJtmGePpmBY/aFDJLAu3HrkbSFFohTwKpboK6DnsHzzJvQ44xxYVQXROvnu+A0L1oV7pkUTtSXWCD40QAA=
before_install:
  - cpanm -n Devel::Cover
  - cpanm -n Devel::Cover::Report::OwnServer
script: perl Build.PL && ./Build && cover -test -report ownServer
